name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Set up JDK 17
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Set up Android SDK with required components
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        components: |
          platforms;android-34
          build-tools;34.0.0
          platform-tools

    # 4️⃣ Auto-increment versionCode/versionName based on Git commits
    - name: Auto versioning
      run: |
        echo "versionCode=$(git rev-list --count HEAD)" >> gradle.properties
        echo "versionName=1.0.$(git rev-list --count HEAD)" >> gradle.properties

    # 5️⃣ Build Debug APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # 6️⃣ Build Release APK
    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    # 7️⃣ Upload Debug APK
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: WhatsappHack-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    # 8️⃣ Upload Release APK
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: WhatsappHack-release.apk
        path: app/build/outputs/apk/release/app-release.apk
